name: First Workflow
on: push
jobs:
 FirstJob:
  runs-on: ubuntu-latest
  steps:
  - name: Get code
    uses: actions/checkout@v3
  - name: Install dependencies
    run: npm ci
  - name: Linting
    run: npm run lint
  - name: Testing
    run: npm run test
  - name: Building
    run: npm run build
  - name: Deployment
    run: echo "Deploying ..."


