name: Issues info
on: 
    issues:
        type: opened
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Print the info
              run: echo "${{toJson(github.event.issue)}}"

